name: Deploy AWS CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: global

      - name: CDK Bootstrap (optional, for first-time deploys or changes)
        run: cdk bootstrap

      - name: Deploy CDK App
        run: cdk deploy --require-approval never
